/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hannu' at '6/11/14 6:08 PM' with Gradle 1.12
 *
 * @author hannu, @date 6/11/14 6:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
