# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "koulutustarjonta" do |koulutustarjonta|

  koulutustarjonta.vm.box = "chef/centos-6.5"

  koulutustarjonta.vm.network :private_network, ip: "10.10.10.10"

    # Sync source code directories from host to guest
    case RUBY_PLATFORM
    when /mswin|msys|mingw|cygwin|bccwin|wince|emc/
      # Fix Windows file rights, otherwise Ansible tries to execute files
      koulutustarjonta.vm.synced_folder "../", "/src", :mount_options => ["dmode=777","fmode=666"]
    else
      # Basic VM synced folder mount
      koulutustarjonta.vm.synced_folder "../", "/src"
    end

  # Ansible provisioning
  koulutustarjonta.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/single-server.yml"
    ansible.inventory_path = "vagrant-inventory"
    ansible.limit = 'all'
  end

  end
  
end
