server:
  adminMinThreads: 1
  adminMaxThreads: 64
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: file
      currentLogFilename: /opt/koulutustarjonta-update/log/koulutustarjonta-update.log
      archivedLogFilenamePattern: /opt/koulutustarjonta-update/log/archive/koulutustarjonta-update-%d.log.gz
      archivedFileCount: 15
      timeZone: UTC

database:
  # the name of your JDBC driver
  driverClass: oracle.jdbc.OracleDriver

  # the username
  user: ${db_user}

  # the password
  password: ${db_passwd}

  # the JDBC URL
  url: ${db_url}

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1 FROM dual"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # log errors when connections fail validation
  logValidationErrors: true

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

tarjontaClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  baseUrl: https://od.helsinki.fi/tarjonta-service/rest/v1/
  opintopolku:
    baseUrl: https://opintopolku.fi

organisaatioClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  baseUrl: https://od.helsinki.fi/organisaatio-service/rest/

koodistoClient:
  timeout: 10000ms
  connectionTimeout: 10000ms
  baseUrl: https://od.helsinki.fi/koodisto-service/rest/json/

sundial:
  thread-pool-size: 5
  shutdown-on-unload: true
  wait-on-shutdown: false
  start-delay-seconds: 0
  start-scheduler-on-load: true
  global-lock-on-load: false

updateCron: 0 0 15 * * ?
