CREATE TABLE KOULUTUS
(
  ID                 VARCHAR2(300 CHAR),
  TAVOITTEET_FI      CLOB,
  TAVOITTEET_EN      CLOB,
  TAVOITTEET_SV      CLOB,
  CONSTRAINT PK_KOULUTUS
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE
)
LOB (TAVOITTEET_FI) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (TAVOITTEET_EN) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (TAVOITTEET_SV) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
