CREATE BIGFILE TABLESPACE bigtbs_01
  DATAFILE 'users.dat'
  SIZE 200M AUTOEXTEND ON;

CREATE USER koultarj
  IDENTIFIED BY koultarj
  DEFAULT TABLESPACE users
  QUOTA 200M ON users;

GRANT CREATE SESSION TO koultarj;
GRANT CREATE TABLE to koultarj;
GRANT CREATE SEQUENCE TO koultarj;
GRANT CREATE TRIGGER TO koultarj;
