--liquibase formatted sql

--changeset hannu:4
ALTER TABLE HAKUKOHDE
  ADD (
    ID_HAKUAIKA VARCHAR2(300 CHAR)
);

ALTER TABLE HAKUKOHDE ADD (
  CONSTRAINT HAKUKOHDE_R02
  FOREIGN KEY (ID_HAKUAIKA)
  REFERENCES HAKUAIKA (ID)
  ENABLE VALIDATE);