--liquibase formatted sql

--changeset jonimake:16

CREATE TABLE KOULUTUS_YHTEYSTIETO_KIELI (
  KOULUTUS_YHTEYSTIETO_ID NUMBER,
  KIELI VARCHAR2(30 CHAR),

  CONSTRAINT FK_KOULUTUS_YHTEYSTIETO
  FOREIGN KEY (KOULUTUS_YHTEYSTIETO_ID)
  REFERENCES KOULUTUS_YHTEYSTIETO (ID)
);

