--liquibase formatted sql

--changeset lauriku:13

CREATE TABLE KOULUTUS_TARJOAJAT (
  ID_KOULUTUS     VARCHAR2(300 CHAR),
  ID_TARJOAJA     VARCHAR2(300 CHAR)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
