--liquibase formatted sql

--changeset jonimake:15

CREATE TABLE KOULUTUS_YHTEYSTIETO (
  ID NUMBER,
  NIMI VARCHAR2(255 CHAR),
  EMAIL VARCHAR2(255 CHAR),
  PUHELINNUMERO VARCHAR2(50 CHAR),
  TYYPPI VARCHAR2(30 CHAR),
  CONSTRAINT PK_KOULUTUS_YHTEYSTIETO_ID PRIMARY KEY (ID)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
