--liquibase formatted sql

--changeset jonimake:19

-- ugly naming but.. oh well
CREATE TABLE KOULUTUS_YHTEYSTIETO_JOIN (
  ID_KOULUTUS VARCHAR2(300 CHAR),
  ID_KOULUTUS_YHTEYSTIETO NUMBER,

  CONSTRAINT FK_KOULUTUS_YHTEYSTIETO_JOIN
  FOREIGN KEY (ID_KOULUTUS_YHTEYSTIETO)
  REFERENCES KOULUTUS_YHTEYSTIETO (ID),

  CONSTRAINT FK_KOULUTUS_JOIN
  FOREIGN KEY (ID_KOULUTUS)
  REFERENCES KOULUTUS (ID)
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;