CREATE TABLE KOULUTUS_POC
(
  ID                 VARCHAR2(300 CHAR),
  TAVOITTEET_FI      CLOB,
  CONSTRAINT PK_KOULUTUS_POC
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE
)
LOB (TAVOITTEET_FI) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
