#!/bin/bash

PIDS=`ps ax | grep 'koulutustarjonta-update.jar' | grep -v grep | grep -o '^[ ]*[0-9]*'`
if [ -n "$PIDS" ]; then
  echo "Stopping koulutustarjonta-update"
  stop koulutustarjonta-update
fi
